use db_cyberkong;

ALTER TABLE t_usuarios MODIFY COLUMN USER_ID INT auto_increment COMMENT 'ID UNICO POR USUARIO';
ALTER TABLE t_usuarios MODIFY COLUMN email varchar(40) COMMENT 'EMAIL DEL USUARIO CON EL QUE LOGEARA';
ALTER TABLE t_usuarios MODIFY COLUMN username varchar(30) COMMENT 'USERNAME CON EL QUE SE IDENTIFICA EL USUARIO';
ALTER TABLE t_usuarios MODIFY COLUMN user_password varchar(65) COMMENT 'CONTRASEÑA CON LA QUE EL USUARIO LOGEARA';
ALTER TABLE t_usuarios MODIFY COLUMN user_nombre varchar(50) COMMENT 'NOMBRE(S) PERSONAL DEL USUARIO';
ALTER TABLE t_usuarios MODIFY COLUMN user_apPat varchar(25) COMMENT 'APELLIDO PATERNO DEL USUARIO';
ALTER TABLE t_usuarios MODIFY COLUMN user_apMat varchar(25) COMMENT 'APELLIDO MATERNO DEL USUARIO (SI LO TIENE)';
ALTER TABLE t_usuarios MODIFY COLUMN user_sex tinyint COMMENT 'SEXO DEL USUARIO';
ALTER TABLE t_usuarios MODIFY COLUMN fecha_nac date COMMENT 'FECHA DE NACIMIENTO DEL USUARIO';
ALTER TABLE t_usuarios MODIFY COLUMN fecha_in datetime COMMENT 'FECHA DE INGRESO DEL USUARIO';
ALTER TABLE t_usuarios MODIFY COLUMN imagen_usuario mediumblob COMMENT 'IMAGEN DEL AVATAR DEL USUARIO';
ALTER TABLE t_usuarios MODIFY COLUMN image_type varchar(15) COMMENT 'TIPO DE ARCHIVO QUE SE USARA PARA EL CONTENT/TYPE';
ALTER TABLE t_usuarios MODIFY COLUMN ROL_ID int COMMENT 'ROL DE USUARIO, SE DEFINE CON LLAVE FORANEA DE TABLA ROL';
ALTER TABLE t_usuarios MODIFY COLUMN ESTADO_ID int COMMENT 'ESTADO DEL USUARIO, SE DEFINE CON LLAVE FORANEA DE TABLA ESTADO';

ALTER TABLE t_carrito MODIFY COLUMN listado_carrito JSON COMMENT 'LISTADO DE PRODUCTOS CON DETALLES PARA SU VENTA, EN FORMATO JSON';
ALTER TABLE t_carrito MODIFY COLUMN USER_ID INT NOT NULL COMMENT 'LLAVE FORANEA DEL USUARIO DUEÑO DEL CARRITO';
ALTER TABLE t_carrito MODIFY COLUMN ESTADO_ID INT COMMENT 'ESTADO EN EL QUE SE ENCUENTRA EL CARRITO';

ALTER TABLE t_categorias MODIFY COLUMN CATEGORIA_ID INT auto_increment COMMENT 'ID UNICO POR CATEGORIA';
ALTER TABLE t_categorias MODIFY COLUMN cat_nombre varchar(20) COMMENT 'NOMBRE DE LA CATEGORIA';
ALTER TABLE t_categorias MODIFY COLUMN cat_descripcion varchar(250) COMMENT 'DESCRIPCION DE LA CATEGORIA';
ALTER TABLE t_categorias MODIFY COLUMN USER_ID int COMMENT 'ID DEL USUARIO QUIEN CREO ESTA CATEGORIA';

ALTER TABLE t_comentarios MODIFY COLUMN COMENTARIO_ID INT auto_increment COMMENT 'ID UNICO DEL COMENTARIO';
ALTER TABLE t_comentarios MODIFY COLUMN com_contenido text COMMENT 'CONTENIDO DEL COMENTARIO';
ALTER TABLE t_comentarios MODIFY COLUMN com_valoracion int COMMENT 'VALORACION DEL PRODUCTO';
ALTER TABLE t_comentarios MODIFY COLUMN com_fecha datetime COMMENT 'FECHA EN QUE SE HIZO EL COMENTARIO';
ALTER TABLE t_comentarios MODIFY COLUMN PRODUCTO_ID int COMMENT 'PRODUCTO AL QUE SE ESTA HACIENDO EL COMENTARIO';
ALTER TABLE t_comentarios MODIFY COLUMN USER_ID int COMMENT 'USUARIO QUIEN ESTA HACIENDO EL COMENTARIO';

ALTER TABLE t_lista_deseados MODIFY COLUMN LISTA_ID int auto_increment COMMENT 'ID UNICO DE LA LISTA DE DESEOS DEL USUARIO';
ALTER TABLE t_lista_deseados MODIFY COLUMN lista_descripcion text COMMENT 'DESCRIPCION DE LA LISTA';
ALTER TABLE t_lista_deseados MODIFY COLUMN lista_longitud int COMMENT 'CANTIDAD DE ARTICULOS EN LA LISTA';
ALTER TABLE t_lista_deseados MODIFY COLUMN USER_ID int COMMENT 'ID DEL USUARIO DUEÑO DE LA LISTA';
ALTER TABLE t_lista_deseados MODIFY COLUMN ESTADO_ID int COMMENT 'ESTADO DE LA LISTA (PUBLICA O PRIVADA)';

ALTER TABLE t_lista_prod MODIFY COLUMN PRODUCTO_ID int COMMENT 'ID DEL PRODUCTO';
ALTER TABLE t_lista_prod MODIFY COLUMN LISTA_ID int COMMENT 'ID DE LA LISTA DONDE SE MOSTRARA ESTE PRODUCTO';
ALTER TABLE t_lista_prod MODIFY COLUMN fecha_ag datetime COMMENT 'FECHA EN LA QUE SE AGREGO EL PRODUCTO A LA LISTA';

ALTER TABLE t_multimedia MODIFY COLUMN MEDIA_ID int auto_increment COMMENT 'ID UNICO DEL ELEMENTO MULTIMEDIA';
ALTER TABLE t_multimedia MODIFY COLUMN media_data longblob COMMENT 'ELEMENTO MULTIMEDIA';
ALTER TABLE t_multimedia MODIFY COLUMN media_type varchar(15) COMMENT 'TIPO DE ELEMENTO MULTIMEDIA';
ALTER TABLE t_multimedia MODIFY COLUMN fecha_subida datetime COMMENT 'FECHA DE SUBIDA DEL ELEMENTO MULTIMEDIA';
ALTER TABLE t_multimedia MODIFY COLUMN PRODUCTO_ID int COMMENT 'ID DEL PRODUCTO AL CUAL PERTENECE ESTE ELEMENTO MULTIMEDIA';

ALTER TABLE t_productos MODIFY COLUMN PRODUCTO_ID int auto_increment COMMENT 'ID UNICO POR PRODUCTO';
ALTER TABLE t_productos MODIFY COLUMN prod_nombre varchar(30) COMMENT 'NOMBRE DEL PRODUCTO';
ALTER TABLE t_productos MODIFY COLUMN prod_description text COMMENT 'DESCRIPCION DEL PRODUCTO';
ALTER TABLE t_productos MODIFY COLUMN precio decimal(8,2) COMMENT 'PRECIO DEL PRODUCTO';
ALTER TABLE t_productos MODIFY COLUMN prod_cantidad int COMMENT 'CANTIDAD DISPONIBLE DE ESTE PRODUCTO';
ALTER TABLE t_productos MODIFY COLUMN prod_valoracion tinyint COMMENT 'VALORACION DEL PRODUCTO (PROMEDIO DE LAS VALORACIONES DE LOS COMENTARIOS DE ESTE PRODUCTO)';
ALTER TABLE t_productos MODIFY COLUMN ESTADO_ID int COMMENT 'ESTADO EN QUE SE ENCUENTRA ESTE PRODUCTO';
ALTER TABLE t_productos MODIFY COLUMN USER_ID int COMMENT 'ID DE USUARIO DUEÑO DE ESTE PRODUCTO (VENDEDOR)';

ALTER TABLE t_cat_prod MODIFY COLUMN CATEGORIA_ID int COMMENT 'ID DE CATEGORIA QUE REPRESENTA LA CATEGORIA ASOCIADA';
ALTER TABLE t_cat_prod MODIFY COLUMN PRODUCTO_ID int COMMENT 'ID DE PRODUCTO QUE REPRESENTA EL PRODUCTO AL QUE SE LE VA ASOCIAR LA CATEGORIA';

ALTER TABLE t_static_rol MODIFY COLUMN ROL_ID int COMMENT 'ID UNICO DEL ROL';
ALTER TABLE t_static_rol MODIFY COLUMN user_rol varchar(10) COMMENT 'NOMBRE/DESCRIPCION QUE LLEVARA EL ROL (EJEMP. "ADMIN")';

ALTER TABLE t_static_state MODIFY COLUMN ESTADO_ID int COMMENT 'ID UNICO DEL ESTADO';
ALTER TABLE t_static_state MODIFY COLUMN descripcion varchar(30) COMMENT 'DESCRIPCION DEL ESTADO (EJEM. "DISPONIBLE")';

ALTER TABLE t_token MODIFY COLUMN TOKEN_ID int auto_increment COMMENT 'ID UNICO DEL TOKEN';
ALTER TABLE t_token MODIFY COLUMN token varchar(45) COMMENT 'TOKEN DE AUTENTIFICACION';
ALTER TABLE t_token MODIFY COLUMN fecha_registro datetime COMMENT 'FECHA EN QUE SE CREO EL TOKEN';
ALTER TABLE t_token MODIFY COLUMN USER_ID int COMMENT 'ID DEL USUARIO AL QUE PERTENECE EL TOKEN';
ALTER TABLE t_token MODIFY COLUMN ESTADO_ID int COMMENT 'ESTADO DEL TOKEN';

ALTER TABLE t_venta MODIFY COLUMN VENTA_ID int auto_increment COMMENT 'ID UNICO DE VENTA';
ALTER TABLE t_venta MODIFY COLUMN fecha_venta date COMMENT 'FECHA EN QUE SE CREO ESTA VENTA';
ALTER TABLE t_venta MODIFY COLUMN USER_ID int COMMENT 'USUARIO PARA OBTENER EL CARRITO AL QUE PERTENECE ESTA VENTA';

ALTER TABLE t_venta_detalle MODIFY COLUMN DETALLE_VENTA_ID int COMMENT 'ID UNICO DE DETALLE VENTA';
ALTER TABLE t_venta_detalle MODIFY COLUMN cantidad int COMMENT 'CANTIDAD DE PRODUCTOS';
ALTER TABLE t_venta_detalle MODIFY COLUMN precio int COMMENT 'PRECIO UNITARIO DEL PRODUCTO';
ALTER TABLE t_venta_detalle MODIFY COLUMN importe int COMMENT 'PRECIO TOTAL POR TODOS LOS PRODUCTOS';
ALTER TABLE t_venta_detalle MODIFY COLUMN VENTA_ID int COMMENT 'VENTA A LA QUE PERTENECE';
ALTER TABLE t_venta_detalle MODIFY COLUMN PRODUCTO_ID int COMMENT 'ID DEL PRODUCTO';

SELECT distinct
t.table_schema AS db_name,
t.table_name,
(case when t.table_type = 'BASE TABLE' then 'table'
when t.table_type = 'VIEW' then 'view'
else t.table_type
end) as table_type,
c.column_name,
c.column_type,
c.column_default,
c.column_key,
c.is_nullable,
c.extra,
c.column_comment
from information_schema.tables as t
inner join information_schema.columns as c
on t.table_name = c.table_name
and t.table_schema = c.table_schema
where t.table_type in ('BASE TABLE')
and t.table_schema = 'db_cyberkong'
order by

t.table_schema,
t.table_name,
c.ordinal_position;
    
